[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
lesson_anchor = "9XtC7LKSJWjfAdJ514EdHhXD3LhvUvBQgpsFVTqJZBvb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"

[test.validator]
bind_address = "127.0.0.1"
